# Generated by Django 6.0.3 on 2026-03-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('request_status', models.CharField(max_length=100)),
                ('technician', models.CharField(blank=True, max_length=200, null=True)),
                ('created_time', models.DateTimeField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('linked_request_id', models.CharField(blank=True, max_length=50, null=True)),
                ('requester', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
