# Generated by Django 5.2.7 on 2026-06-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_resolved_time_alter_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolved_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
